#!/bin/env python
# event implementation for openttd-python bot script

from ottd_lib import LOG
import ottd_constants as const
from ottd_config import config
import StringIO
import traceback

class Event:
    dispatchTo = ["sendToGame", "sendToIRC", "sendToLog", "sendToCmdProc"]
    def dispatch(self):
        for to in self.dispatchTo:
            if not type(to) == str:
                to(self)
            else:
                try:
                    function = getattr(self, to)
                except AttributeError:
                    LOG.error("Unknown dispatcher in %s: %s" % (self.__class__, to))
                else:
                    function()
    def sendToCmdProc(self):
        if self.parentclient is None:
            return False
        self.parentclient.processCommand(self)
        return True
class IngameChat(Event):
    """
        this event is generated by ingame chat
    """
    dispatchTo = ["sendToIRC", "sendToLog", "sendToCmdProc"]
    def __init__(self, msg, clientid=-1, parent=None, parentclient=None, type=None):
        self.type = type
        self.parentclient = parentclient
        self.parent = parent
        if not parent is None:
            # get stuff from parents
            try:
                if type is None and not self.parent.type is None:
                    self.type = self.parent.type
                if parentclient is None and not self.parent.parentclient is None:
                    self.parentclient = self.parent.parentclient
                if clientid == -1 and not self.parent.playerid == -1:
                    clientid = self.parent.playerid
                elif clientid == -1 and not self.parentclient is None:
                    clientid = self.parentclient.client_id
            except AttributeError:
                pass
        self.playerid = clientid
        self.msg = msg
        if clientid in self.parentclient.playerlist:
            self.playername = self.parentclient.playerlist[clientid]['name']
            self.playercompany = self.parentclient.playerlist[clientid]['company']
        self.dispatch()
    
    def __repr__(self):
        return "IngameChat<msg='%s', playerid=%d, playername='%s', self_sent=%d, broadcast=%d, distribution=%s>" % (
                    self.msg,
                    self.playerid,
                    self.playername,
                    self.self_sent,
                    self.broadcast,
                    self.distribution
                )
    def isCommand(self):
        return self.msg.startswith(config.get("main", "commandprefix"))
    def respond(self, msg):
        if not self.type is None:
            if self.type == "public" or self.type == "team":
                IngameChatResponse("%s: %s" % (self.playername, msg), self.playerid, self)
            elif self.type == "private":
                IngameChatResponse(msg, self.playerid, self)
    def sendToGame(self):
        if not self.type is None:
            if self.type == "public":
                self.parentclient.sendChat(self.msg)
            elif self.type == "team":
                self.parentclient.sendChat(self.msg, desttype=const.DESTTYPE_TEAM, dest=self.playercompany, chattype=const.NETWORK_ACTION_CHAT_COMPANY)
            elif self.type == "private":
                self.parentclient.sendChat(self.msg, desttype=const.DESTTYPE_CLIENT, dest=self.playerid, chattype=const.NETWORK_ACTION_CHAT_CLIENT)
            return True
    def sendToLog(self):
        if not self.type is None:
            if self.type == "public":
                LOG.info("Ingame chat: <%s> %s" % (self.playername,self.msg))
            elif self.type == "team":
                LOG.info("Ingame company chat: [%d]<%s> %s" % (self.playercompany, self.playername,self.msg))
            elif self.type == "private":
                LOG.info("Ingame private chat: <%s> %s" % (self.playername,self.msg))
            return True
    def sendToIRC(self):
        if self.parentclient.irc is None or self.isCommand():
            return False
        if not self.type is None:
            if self.type == "public":
                self.parentclient.irc.say("<%s> %s" % (self.playername, self.msg), 0)   
            elif self.type == "team":
                self.parentclient.irc.say("[company: %d]<%s> %s" % (self.playercompany,self.playername, self.msg), 0)
            elif self.type == "private":
                if self.playername in self.parentclient.irc.bridges_ingame_irc:
                    self.parentclient.irc.say_nick(self.parentclient.irc.bridges_ingame_irc[self.playername], "[bridge] <%s> %s" % (self.playername, self.msg), 0)
                else:
                    self.parentclient.irc.say("[private]<%s> %s" % (self.playername, self.msg), 0)
    def isByOp(self):
        return self.playerid == 1
    def isFromIRC(self):
        return False


class IngameChatResponse(IngameChat):
    dispatchTo = ["sendToGame", "sendToLog"]
    def respond(self, msg):
        pass
    def sendToLog(self):
        if self.type is None:
            return False
        if self.type == "public":
            LOG.info("Ingame public chat response: %s" % (self.msg))
        elif self.type == "team":
            LOG.info("Ingame team chat response: <To: %s> %s" % (self.playercompany, self.msg))
        elif self.type == "private":
            LOG.info("Ingame private chat response: <To: %s> %s" % (self.playername, self.msg))

        
class IRCChat(Event):
    """
        event generated by IRC chat
    """
    dispatchTo = ["sendToLog", "sendToCmdProc"]
    type = None
    playerid = -1
    def __init__(self, msg, nickname, parentclient=None, parent=None, parentircevent=None):
        if parentclient is None and not parent is None:
            self.parentclient = parent.parentclient
        else:
            self.parentclient = parentclient
        if parentircevent is None and not parent is None:
            self.parentircevent = parent.parentircevent
        else:
            self.parentircevent = parentircevent
        self.playername = nickname
        self.msg = msg
        self.parent = parent
        self.dispatch()
    def isCommand(self):
        return self.msg.startswith(config.get("main", "commandprefix"))
    def sendToGame(self):
        if self.isCommand(): # don't forward commands to game
            return False
        self.parentclient.sendChat("<%s> %s" % (self.playername, self.msg))
        return True
    def sendToIRC(self):
        if self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say(self.msg, 0)
    def isFromIRC(self):
        return True
class IRCPublicChat(IRCChat):
    """
        event is generated by IRC channel chat
    """
    dispatchTo = ["sendToGame", "sendToLog", "sendToCmdProc"]
    type = None
    playerid = -1
    def __init__(self, msg, nickname, parentclient=None, parent=None, parentircevent=None):
        if parentclient is None and not parent is None:
            self.parentclient = parent.parentclient
        else:
            self.parentclient = parentclient
        if parentircevent is None and not parent is None:
            self.parentircevent = parent.parentircevent
        else:
            self.parentircevent = parentircevent
        self.playername = nickname
        self.msg = msg
        self.parent = parent
        self.dispatch()
    def isCommand(self):
        return self.msg.startswith(config.get("main", "commandprefix"))
    def sendToGame(self):
        if self.isCommand(): # don't forward commands to game
            return False
        self.parentclient.sendChat("<%s> %s" % (self.playername, self.msg))
        return True
    def sendToIRC(self):
        if self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say(self.msg, 0)
    def sendToLog(self):
        LOG.info("IRC chat: <%s> %s" % (self.playername,self.msg))
        return True
    def respond(self, msg):
        IRCPublicChatResponse("%s: %s" % (self.playername, msg),self.playername, parent=self)
    def isByOp(self):
        if self.parentclient is None or self.parentircevent is None:
            return False
        return self.parentclient.irc.bot.channels[self.parentircevent.target()].is_oper(self.playername)

class IRCPublicChatResponse(IRCPublicChat):
    dispatchTo = ["sendToIRC", "sendToLog"]
    def sendToLog(self):
        LOG.info("IRC chat response: %s" % self.msg)

class IRCPrivateChat(IRCChat):
    """
        event is generated by IRC private chat
    """
    dispatchTo = ["sendToLog", "sendToGame", "sendToCmdProc"]
    def sendToLog(self):
        LOG.info("IRC private chat: <%s> %s" % (self.playername,self.msg))
        return True
    def sendToGame(self):
        if self.playername in self.parentclient.irc.bridges_irc_ingame and not self.isCommand():
            playername = self.parentclient.irc.bridges_irc_ingame[self.playername]
            for client in self.parentclient.playerlist:
                if self.parentclient.playerlist[client]['name'] == playername:
                    self.parentclient.sendChat("[bridge] <%s> %s" % (self.playername, self.msg), desttype=const.DESTTYPE_CLIENT, dest=self.parentclient.playerlist[client]['id'], chattype=const.NETWORK_ACTION_CHAT_CLIENT)
                    break;
    def respond(self, msg):
        IRCPrivateChatResponse(msg,self.playername, parent=self)
    def isByOp(self):
        return False

class IRCPrivateChatResponse(IRCPrivateChat):
    dispatchTo = ["sendToIRC", "sendToLog"]
    def sendToLog(self):
        LOG.info("IRC private chat response to %s: %s" % (self.playername, self.msg))
    def sendToIRC(self):
        if self.parentclient.irc is None:
            return False
        self.parentclient.irc.say_nick(self.playername, self.msg, 0)

class IRCPrivateNoticeChat(IRCPrivateChat):
    """
        event is generated by IRC notice chat
    """
    def respond(self, msg):
        IRCPrivateNoticeChatResponse(msg,self.playername, parent=self)
class IRCPrivateNoticeChatResponse(IRCPrivateChatResponse):
    def sendToIRC(self):
        if self.parentclient.irc is None:
            return False
        self.parentclient.irc.notice(self.playername, self.msg)
        
class Broadcast(IngameChat):
    """
        this event is generated by the bot itself when it needs to broadcast something
    """
    dispatchTo = ["sendToGame", "sendToIRC", "sendToLog"]
    def sendToGame(self):
        self.parentclient.sendChat(self.msg)
        return True
    def sendToIRC(self):
        if self.parentclient.irc is None:
            return False
        self.parentclient.irc.say(self.msg, 0)
    def sendToLog(self):
        LOG.info("EVENT: %s" % (self.msg))
        return True

        
class IngameToIRC(Broadcast):
    """
        this event is generated by join/quit messages
    """
    dispatchTo = ["sendToIRC", "sendToLog"]
class IRCToIngame(Broadcast):
    """
        this event is generated by internal messages from irc"
    """
    dispatchTo = ["sendToGame", "sendToLog"]
class IRCPublicActionChat(IRCPublicChat):
    """
        this event is generated by irc /me messages
    """
    dispatchTo = ["sendToGame", "sendToLog"]
    def sendToGame(self):
        self.parentclient.sendChat("* %s %s" % (self.playername, self.msg))
    def sendToLog(self):
        LOG.info("IRC action: * %s %s" % (self.playername, self.msg))
class IRCPrivateActionChat(IRCPrivateChat):
    """
        this event is generated by irc private /me messages
    """
    dispatchTo = ["sendToLog"]
    def sendToLog(self):
        LOG.info("IRC private action: * %s %s" % (self.playername, self.msg))
class InternalCommand(Event):
    dispatchTo = ["sendToCmdProc"]
    def __init__(self, msg, parentclient=None):
        self.msg = msg
        self.parentclient = parentclient
        self.dispatch()
    def respond(self, msg):
        # this should not happen.
        Broadcast(msg, parentclient=self.parentclient, parent=self)
    def isByOp(self):
        return True
    def isCommand(self):
        return True
    def isFromIRC(self):
        return False
