#!/bin/env python
# event implementation for openttd-python bot script

from ottd_lib import LOG
import ottd_constants as const
from ottd_config import config

class Event:
    msg=None    # the text
    type=None    # type (not used yet)
    source=None    # source (not used yet)
    parent=None    #the parent event
    parentclient=None
    self_sent=False
    broadcast=0    # publish to all or just to the parent event's owner?
    """
        0 = all
        1 = private
        2 = team
    """

class IngameChatEvent(Event):
    """
        this event is generated by ingame chat
    """
    execute = True
    distribution = {'ingame': False, 'irc': True, 'log': True}
    def __init__(self, msg, clientid=-1, parent=None, parentclient=None):
        if parentclient is None and not parent is None:
            self.parentclient = parent.parentclient
        else:
            self.parentclient = parentclient
        if not self.parentclient is None and clientid == -1:
            clientid = self.parentclient.client_id
        self.playerid = clientid
        self.msg = msg
        if not self.parentclient is None and clientid in self.parentclient.playerlist:
            self.playername = self.parentclient.playerlist[clientid]['name']
            self.playercompany = self.parentclient.playerlist[clientid]['company']
        self.dispatch()
    def __name__(self):
        return "IngameChatEvent"
    
    def __repr__(self):
        return "IngameChatEvent<msg='%s', playerid=%d, playername='%s', self_sent=%d, broadcast=%d, distribution=%s>" % (
                    self.msg,
                    self.playerid,
                    self.playername,
                    self.self_sent,
                    self.broadcast,
                    self.distribution
                )
    def isCommand(self):
        return self.msg.startswith(config.get("main", "commandprefix"))
    def dispatch(self):
        self.sendToGame()
        self.sendToLog()
        self.sendToIRC()
        if self.execute:
            self.parentclient.processCommand(self)

class IngameOwnGeneratedEvent:
    distribution = {'ingame': True, 'irc': False, 'log': True}
    execute = False
    def respond(self, msg):
        pass
		

class IngamePublicChatEvent(IngameChatEvent):
    """
        this event is generated by ingame public chat
    """
    def __name__(self):
        return "IngamePublicChatEvent"
    def respond(self, msg):
        if self.parentclient is None:
            return
        IngamePublicChatEventResponse("%s: %s" % (self.playername, msg), self.playerid, self)
    def sendToGame(self):
        if not self.distribution['ingame']:
            return False
        if self.parentclient is None:
            return False
        self.parentclient.sendChat(self.msg)
        return True
    def sendToIRC(self):
        if not self.distribution['irc'] or self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say("<%s> %s" % (self.playername, self.msg), 0)
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame chat: <%s> %s" % (self.playername,self.msg))
        return True
		

class IngamePublicChatEventResponse(IngameOwnGeneratedEvent, IngamePublicChatEvent):
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame public chat response: %s" % (self.msg))

class IngameTeamChatEvent(IngameChatEvent):
    """
        this event is generated by ingame company chat
    """
    def __name__(self):
        return "IngameTeamChatEvent"
    def respond(self, msg):
        if self.parentclient is None:
            return
        IngameTeamChatEventResponse("%s: %s" % (self.playername,msg), self.playerid, self)
    def sendToGame(self):
        if not self.distribution['ingame']:
            return False
        if self.parentclient is None:
            return False
        self.parentclient.sendChat(self.msg, desttype=const.DESTTYPE_TEAM, dest=self.playercompany, chattype=const.NETWORK_ACTION_CHAT_COMPANY)
        return True
    def sendToIRC(self):
        if not self.distribution['irc'] or self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say("[company: %d]<%s> %s" % (self.playercompany,self.playername, self.msg), 0)
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame company chat: [%d]<%s> %s" % (self.playercompany, self.playername,self.msg))
        return True

class IngameTeamChatEventResponse(IngameOwnGeneratedEvent, IngameTeamChatEvent):
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame team chat response: <To: %s> %s" % (self.playercompany, self.msg))

class IngamePrivateChatEvent(IngameChatEvent):
    """
        this event is generated by ingame private chat
    """
    def __name__(self):
        return "IngamePrivateChatEvent"
    def respond(self, msg):
        if self.parentclient is None:
            return
        IngamePrivateChatEventResponse(msg, self.playerid, self)
    def sendToGame(self):
        if not self.distribution['ingame']:
            return False
        if self.parentclient is None:
            return False
        if not self.distribution['ingame'] or self.parentclient is None:
            return False
        self.parentclient.sendChat(self.msg, desttype=const.DESTTYPE_CLIENT, dest=self.playerid, chattype=const.NETWORK_ACTION_CHAT_CLIENT)
        return True
    def sendToIRC(self):
        if not self.distribution['irc'] or self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say("[private]<%s> %s" % (self.playername, self.msg), 0)
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame private chat: <%s> %s" % (self.playername,self.msg))
        return True


class IngamePrivateChatEventResponse(IngameOwnGeneratedEvent, IngamePrivateChatEvent):
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("Ingame private chat response: <To: %s> %s" % (self.playername, self.msg))

class IRCPublicChatEvent:
    """
        event is generated by IRC channel chat
    """
    distribution = {'ingame': True, 'irc': False, 'log': True}
    execute = True
    def __init__(self, msg, nickname, parentclient=None, parent=None):
        if parentclient is None and not parent is None:
            self.parentclient = parent.parentclient
        else:
            self.parentclient = parentclient
        self.playername = nickname
        self.msg = msg
        self.parent = parent
        self.dispatch()
    def isCommand(self):
        return self.msg.startswith(config.get("main", "commandprefix"))
    def sendToGame(self):
        if not self.distribution['ingame'] or self.isCommand(): # don't forward commands to game
            return False
        if self.parentclient is None:
            return False
        self.parentclient.sendChat("<%s> %s" % (self.playername, self.msg))
        return True
    def sendToIRC(self):
        if not self.distribution['irc'] or self.parentclient.irc is None or self.isCommand():
            return False
        self.parentclient.irc.say(self.msg, 0)
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("IRC chat: <%s> %s" % (self.playername,self.msg))
        return True
    def respond(self, msg):
        IRCPublicChatEventResponse("%s: %s" % (self.playername, msg),self.playername, parent=self)
    def dispatch(self):
        self.sendToGame()
        self.sendToLog()
        self.sendToIRC()
        if self.execute:
            self.parentclient.processCommand(self)
			

class IRCPublicChatEventResponse(IRCPublicChatEvent):
    distribution = {'ingame': False, 'irc': True, 'log': True}
    execute = False
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("IRC chat response: %s" % self.msg)
		
		
class BroadcastEvent(IngameChatEvent):
    """
        this event is generated by the bot itself when it needs to broadcast something
    """
    distribution = {'ingame': True, 'irc': True, 'log': True}
    execute = False
    def sendToGame(self):
        if not self.distribution['ingame']:
            return False
        if self.parentclient is None:
            return False
        self.parentclient.sendChat(self.msg)
        return True
    def sendToIRC(self):
        if not self.distribution['irc'] or self.parentclient.irc is None:
            return False
        self.parentclient.irc.say(self.msg, 0)
    def sendToLog(self):
        if not self.distribution['log']:
            return False
        LOG.info("EVENT: %s" % (self.msg))
        return True
		
		
class IngameToIRCEvent(BroadcastEvent):
    """
        this event is generated by join/quit messages
    """
    distribution = {'ingame': False, 'irc': True, 'log': True}
class InternalCommandEvent(Event):
    def __init__(self, msg, parentclient=None):
        self.msg = msg
        self.parentclient = parentclient
        self.dispatch()
    def dispatch(self):
        self.parentclient.processCommand(self)
	def respond(self, msg):
        pass
    def __name__(self):
	    return "BotEvent"